version: '2'
services:
  dataintegration1-app:
    image: dataintegration1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dataintegration1-postgresql:5432/dataintegration1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  dataintegration1-postgresql:
    extends:
      file: postgresql.yml
      service: dataintegration1-postgresql
